/**
 * Auto-generated from dml-chartDrawing.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const dmlChartDrawingSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/drawingml/chartDrawing",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/drawingml/main",
      "schemaLocation": "dml-main.xsd"
    }
  ],
  "simpleTypes": [
    {
      "name": "ST_MarkerCoordinate",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "double"
        },
        "facets": [
          {
            "kind": "minInclusive",
            "value": "0.0",
            "fixed": false
          },
          {
            "kind": "maxInclusive",
            "value": "1.0",
            "fixed": false
          }
        ]
      }
    }
  ],
  "complexTypes": [
    {
      "name": "CT_ShapeNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualDrawingShapeProps",
              "name": "cNvSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Shape",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "macro",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "textlink",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "fLocksText",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "true"
        },
        {
          "name": "fPublished",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_ShapeNonVisual",
              "name": "nvSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeProperties",
              "name": "spPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeStyle",
              "name": "style",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_TextBody",
              "name": "txBody",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_ConnectorNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualConnectorProperties",
              "name": "cNvCxnSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Connector",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "macro",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "fPublished",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_ConnectorNonVisual",
              "name": "nvCxnSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeProperties",
              "name": "spPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeStyle",
              "name": "style",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_PictureNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualPictureProperties",
              "name": "cNvPicPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Picture",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "macro",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional",
          "default": ""
        },
        {
          "name": "fPublished",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_PictureNonVisual",
              "name": "nvPicPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_BlipFillProperties",
              "name": "blipFill",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeProperties",
              "name": "spPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeStyle",
              "name": "style",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GraphicFrameNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualGraphicFrameProperties",
              "name": "cNvGraphicFramePr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GraphicFrame",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "macro",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "fPublished",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_GraphicFrameNonVisual",
              "name": "nvGraphicFramePr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_Transform2D",
              "name": "xfrm",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "a:graphic",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GroupShapeNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualGroupDrawingShapeProps",
              "name": "cNvGrpSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GroupShape",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_GroupShapeNonVisual",
              "name": "nvGrpSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_GroupShapeProperties",
              "name": "grpSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "CT_Shape",
                  "name": "sp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_GroupShape",
                  "name": "grpSp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_GraphicFrame",
                  "name": "graphicFrame",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_Connector",
                  "name": "cxnSp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_Picture",
                  "name": "pic",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Marker",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "ST_MarkerCoordinate",
              "name": "x",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "ST_MarkerCoordinate",
              "name": "y",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_RelSizeAnchor",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Marker",
              "name": "from",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_Marker",
              "name": "to",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_ObjectChoices"
              },
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_AbsSizeAnchor",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Marker",
              "name": "from",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_PositiveSize2D",
              "name": "ext",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_ObjectChoices"
              },
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Drawing",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_Anchor"
              },
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [],
  "groups": [
    {
      "name": "EG_ObjectChoices",
      "compositor": {
        "kind": "sequence",
        "particles": [
          {
            "kind": "choice",
            "particles": [
              {
                "type": "CT_Shape",
                "name": "sp",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_GroupShape",
                "name": "grpSp",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_GraphicFrame",
                "name": "graphicFrame",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_Connector",
                "name": "cxnSp",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_Picture",
                "name": "pic",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              }
            ],
            "minOccurs": 1,
            "maxOccurs": 1
          }
        ],
        "minOccurs": 1,
        "maxOccurs": 1
      }
    },
    {
      "name": "EG_Anchor",
      "compositor": {
        "kind": "choice",
        "particles": [
          {
            "type": "CT_RelSizeAnchor",
            "name": "relSizeAnchor",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_AbsSizeAnchor",
            "name": "absSizeAnchor",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          }
        ],
        "minOccurs": 1,
        "maxOccurs": 1
      }
    }
  ],
  "attributeGroups": []
}

export default dmlChartDrawingSchema