/**
 * Auto-generated from dml-spreadsheetDrawing.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const dmlSpreadsheetDrawingSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/drawingml/spreadsheetDrawing",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/drawingml/main",
      "schemaLocation": "dml-main.xsd"
    },
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/relationships",
      "schemaLocation": "shared-relationshipReference.xsd"
    }
  ],
  "simpleTypes": [
    {
      "name": "ST_ColID",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "int"
        },
        "facets": [
          {
            "kind": "minInclusive",
            "value": "0",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_RowID",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "int"
        },
        "facets": [
          {
            "kind": "minInclusive",
            "value": "0",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_EditAs",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "token"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "twoCell",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "oneCell",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "absolute",
            "fixed": false
          }
        ]
      }
    }
  ],
  "complexTypes": [
    {
      "name": "CT_AnchorClientData",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "fLocksWithSheet",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "true"
        },
        {
          "name": "fPrintsWithSheet",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "true"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_ShapeNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualDrawingShapeProps",
              "name": "cNvSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Shape",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "macro",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "textlink",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "fLocksText",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "true"
        },
        {
          "name": "fPublished",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_ShapeNonVisual",
              "name": "nvSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeProperties",
              "name": "spPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeStyle",
              "name": "style",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_TextBody",
              "name": "txBody",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_ConnectorNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualConnectorProperties",
              "name": "cNvCxnSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Connector",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "macro",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "fPublished",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_ConnectorNonVisual",
              "name": "nvCxnSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeProperties",
              "name": "spPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeStyle",
              "name": "style",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_PictureNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualPictureProperties",
              "name": "cNvPicPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Picture",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "macro",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional",
          "default": ""
        },
        {
          "name": "fPublished",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_PictureNonVisual",
              "name": "nvPicPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_BlipFillProperties",
              "name": "blipFill",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeProperties",
              "name": "spPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeStyle",
              "name": "style",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GraphicalObjectFrameNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualGraphicFrameProperties",
              "name": "cNvGraphicFramePr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GraphicalObjectFrame",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "macro",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "fPublished",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_GraphicalObjectFrameNonVisual",
              "name": "nvGraphicFramePr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_Transform2D",
              "name": "xfrm",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "a:graphic",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GroupShapeNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualGroupDrawingShapeProps",
              "name": "cNvGrpSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GroupShape",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_GroupShapeNonVisual",
              "name": "nvGrpSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_GroupShapeProperties",
              "name": "grpSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "CT_Shape",
                  "name": "sp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_GroupShape",
                  "name": "grpSp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_GraphicalObjectFrame",
                  "name": "graphicFrame",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_Connector",
                  "name": "cxnSp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_Picture",
                  "name": "pic",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Rel",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "",
          "ref": {
            "kind": "external",
            "prefix": "r",
            "name": "id"
          },
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Marker",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "ST_ColID",
              "name": "col",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:ST_Coordinate",
              "name": "colOff",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "ST_RowID",
              "name": "row",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:ST_Coordinate",
              "name": "rowOff",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_TwoCellAnchor",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "editAs",
          "type": {
            "kind": "local",
            "name": "ST_EditAs"
          },
          "use": "optional",
          "default": "twoCell"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Marker",
              "name": "from",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_Marker",
              "name": "to",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_AnchorClientData",
              "name": "clientData",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_ObjectChoices"
              },
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_OneCellAnchor",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Marker",
              "name": "from",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_PositiveSize2D",
              "name": "ext",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_AnchorClientData",
              "name": "clientData",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_ObjectChoices"
              },
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_AbsoluteAnchor",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_Point2D",
              "name": "pos",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_PositiveSize2D",
              "name": "ext",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_AnchorClientData",
              "name": "clientData",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_ObjectChoices"
              },
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Drawing",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_Anchor"
              },
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [
    {
      "name": "from",
      "type": {
        "kind": "local",
        "name": "CT_Marker"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "to",
      "type": {
        "kind": "local",
        "name": "CT_Marker"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "wsDr",
      "type": {
        "kind": "local",
        "name": "CT_Drawing"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [
    {
      "name": "EG_ObjectChoices",
      "compositor": {
        "kind": "sequence",
        "particles": [
          {
            "kind": "choice",
            "particles": [
              {
                "type": "CT_Shape",
                "name": "sp",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_GroupShape",
                "name": "grpSp",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_GraphicalObjectFrame",
                "name": "graphicFrame",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_Connector",
                "name": "cxnSp",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_Picture",
                "name": "pic",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_Rel",
                "name": "contentPart",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              }
            ],
            "minOccurs": 1,
            "maxOccurs": 1
          }
        ],
        "minOccurs": 1,
        "maxOccurs": 1
      }
    },
    {
      "name": "EG_Anchor",
      "compositor": {
        "kind": "choice",
        "particles": [
          {
            "type": "CT_TwoCellAnchor",
            "name": "twoCellAnchor",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_OneCellAnchor",
            "name": "oneCellAnchor",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_AbsoluteAnchor",
            "name": "absoluteAnchor",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          }
        ],
        "minOccurs": 1,
        "maxOccurs": 1
      }
    }
  ],
  "attributeGroups": []
}

export default dmlSpreadsheetDrawingSchema