/**
 * Auto-generated from dml-wordprocessingDrawing.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const dmlWordprocessingDrawingSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/drawingml/wordprocessingDrawing",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/drawingml/main",
      "schemaLocation": "dml-main.xsd"
    },
    {
      "namespace": "http://purl.oclc.org/ooxml/wordprocessingml/main",
      "schemaLocation": "wml.xsd"
    },
    {
      "namespace": "http://purl.oclc.org/ooxml/drawingml/picture",
      "schemaLocation": "dml-picture.xsd"
    },
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/relationships",
      "schemaLocation": "shared-relationshipReference.xsd"
    }
  ],
  "simpleTypes": [
    {
      "name": "ST_WrapDistance",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "unsignedInt"
        },
        "facets": []
      }
    },
    {
      "name": "ST_WrapText",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "token"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "bothSides",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "left",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "right",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "largest",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_PositionOffset",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "int"
        },
        "facets": []
      }
    },
    {
      "name": "ST_AlignH",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "token"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "left",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "right",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "center",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "inside",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "outside",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_RelFromH",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "token"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "margin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "page",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "column",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "character",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "leftMargin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "rightMargin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "insideMargin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "outsideMargin",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_AlignV",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "token"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "top",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bottom",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "center",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "inside",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "outside",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_RelFromV",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "token"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "margin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "page",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "paragraph",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "line",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "topMargin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bottomMargin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "insideMargin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "outsideMargin",
            "fixed": false
          }
        ]
      }
    }
  ],
  "complexTypes": [
    {
      "name": "CT_EffectExtent",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "l",
          "type": {
            "kind": "external",
            "prefix": "a",
            "name": "ST_Coordinate"
          },
          "use": "required"
        },
        {
          "name": "t",
          "type": {
            "kind": "external",
            "prefix": "a",
            "name": "ST_Coordinate"
          },
          "use": "required"
        },
        {
          "name": "r",
          "type": {
            "kind": "external",
            "prefix": "a",
            "name": "ST_Coordinate"
          },
          "use": "required"
        },
        {
          "name": "b",
          "type": {
            "kind": "external",
            "prefix": "a",
            "name": "ST_Coordinate"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Inline",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "distT",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distB",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distL",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distR",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_PositiveSize2D",
              "name": "extent",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_EffectExtent",
              "name": "effectExtent",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "docPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualGraphicFrameProperties",
              "name": "cNvGraphicFramePr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "a:graphic",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WrapPath",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "edited",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_Point2D",
              "name": "start",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_Point2D",
              "name": "lineTo",
              "minOccurs": 2,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WrapNone",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_WrapSquare",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "wrapText",
          "type": {
            "kind": "local",
            "name": "ST_WrapText"
          },
          "use": "required"
        },
        {
          "name": "distT",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distB",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distL",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distR",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_EffectExtent",
              "name": "effectExtent",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WrapTight",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "wrapText",
          "type": {
            "kind": "local",
            "name": "ST_WrapText"
          },
          "use": "required"
        },
        {
          "name": "distL",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distR",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_WrapPath",
              "name": "wrapPolygon",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WrapThrough",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "wrapText",
          "type": {
            "kind": "local",
            "name": "ST_WrapText"
          },
          "use": "required"
        },
        {
          "name": "distL",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distR",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_WrapPath",
              "name": "wrapPolygon",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WrapTopBottom",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "distT",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distB",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_EffectExtent",
              "name": "effectExtent",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_PosH",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "relativeFrom",
          "type": {
            "kind": "local",
            "name": "ST_RelFromH"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "ST_AlignH",
                  "name": "align",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "ST_PositionOffset",
                  "name": "posOffset",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_PosV",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "relativeFrom",
          "type": {
            "kind": "local",
            "name": "ST_RelFromV"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "ST_AlignV",
                  "name": "align",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "ST_PositionOffset",
                  "name": "posOffset",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Anchor",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "distT",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distB",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distL",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "distR",
          "type": {
            "kind": "local",
            "name": "ST_WrapDistance"
          },
          "use": "optional"
        },
        {
          "name": "simplePos",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional"
        },
        {
          "name": "relativeHeight",
          "type": {
            "kind": "builtin",
            "name": "unsignedInt"
          },
          "use": "required"
        },
        {
          "name": "behindDoc",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "required"
        },
        {
          "name": "locked",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "required"
        },
        {
          "name": "layoutInCell",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "required"
        },
        {
          "name": "hidden",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional"
        },
        {
          "name": "allowOverlap",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_Point2D",
              "name": "simplePos",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_PosH",
              "name": "positionH",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_PosV",
              "name": "positionV",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_PositiveSize2D",
              "name": "extent",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_EffectExtent",
              "name": "effectExtent",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "docPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualGraphicFrameProperties",
              "name": "cNvGraphicFramePr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "a:graphic",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_WrapType"
              },
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_TxbxContent",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_TextboxInfo",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "id",
          "type": {
            "kind": "builtin",
            "name": "unsignedShort"
          },
          "use": "optional",
          "default": "0"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_TxbxContent",
              "name": "txbxContent",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_OfficeArtExtensionList",
              "name": "extLst",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_LinkedTextboxInformation",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "id",
          "type": {
            "kind": "builtin",
            "name": "unsignedShort"
          },
          "use": "required"
        },
        {
          "name": "seq",
          "type": {
            "kind": "builtin",
            "name": "unsignedShort"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_OfficeArtExtensionList",
              "name": "extLst",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WordprocessingShape",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "normalEastAsianFlow",
          "type": {
            "kind": "builtin",
            "name": "boolean"
          },
          "use": "optional",
          "default": "false"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeProperties",
              "name": "spPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_ShapeStyle",
              "name": "style",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_OfficeArtExtensionList",
              "name": "extLst",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_TextBodyProperties",
              "name": "bodyPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "a:CT_NonVisualDrawingShapeProps",
                  "name": "cNvSpPr",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "a:CT_NonVisualConnectorProperties",
                  "name": "cNvCnPr",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 1,
              "maxOccurs": 1
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "CT_TextboxInfo",
                  "name": "txbx",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_LinkedTextboxInformation",
                  "name": "linkedTxbx",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GraphicFrame",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualGraphicFrameProperties",
              "name": "cNvFrPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_Transform2D",
              "name": "xfrm",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "a:graphic",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_OfficeArtExtensionList",
              "name": "extLst",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WordprocessingContentPartNonVisual",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualContentPartProperties",
              "name": "cNvContentPartPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WordprocessingContentPart",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "bwMode",
          "type": {
            "kind": "external",
            "prefix": "a",
            "name": "ST_BlackWhiteMode"
          },
          "use": "optional"
        },
        {
          "name": "",
          "ref": {
            "kind": "external",
            "prefix": "r",
            "name": "id"
          },
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_WordprocessingContentPartNonVisual",
              "name": "nvContentPartPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_Transform2D",
              "name": "xfrm",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_OfficeArtExtensionList",
              "name": "extLst",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WordprocessingGroup",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_NonVisualDrawingProps",
              "name": "cNvPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_NonVisualGroupDrawingShapeProps",
              "name": "cNvGrpSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_GroupShapeProperties",
              "name": "grpSpPr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_OfficeArtExtensionList",
              "name": "extLst",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "name": "",
                  "ref": "wsp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_WordprocessingGroup",
                  "name": "grpSp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_GraphicFrame",
                  "name": "graphicFrame",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "name": "",
                  "ref": "dpct:pic",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_WordprocessingContentPart",
                  "name": "contentPart",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_WordprocessingCanvas",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "a:CT_BackgroundFormatting",
              "name": "bg",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_WholeE2oFormatting",
              "name": "whole",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "a:CT_OfficeArtExtensionList",
              "name": "extLst",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "name": "",
                  "ref": "wsp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "name": "",
                  "ref": "dpct:pic",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_WordprocessingContentPart",
                  "name": "contentPart",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "name": "",
                  "ref": "wgp",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_GraphicFrame",
                  "name": "graphicFrame",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [
    {
      "name": "wpc",
      "type": {
        "kind": "local",
        "name": "CT_WordprocessingCanvas"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "wgp",
      "type": {
        "kind": "local",
        "name": "CT_WordprocessingGroup"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "wsp",
      "type": {
        "kind": "local",
        "name": "CT_WordprocessingShape"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "inline",
      "type": {
        "kind": "local",
        "name": "CT_Inline"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "anchor",
      "type": {
        "kind": "local",
        "name": "CT_Anchor"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [
    {
      "name": "EG_WrapType",
      "compositor": {
        "kind": "sequence",
        "particles": [
          {
            "kind": "choice",
            "particles": [
              {
                "type": "CT_WrapNone",
                "name": "wrapNone",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_WrapSquare",
                "name": "wrapSquare",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_WrapTight",
                "name": "wrapTight",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_WrapThrough",
                "name": "wrapThrough",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              },
              {
                "type": "CT_WrapTopBottom",
                "name": "wrapTopAndBottom",
                "minOccurs": 1,
                "maxOccurs": 1,
                "nillable": false
              }
            ],
            "minOccurs": 1,
            "maxOccurs": 1
          }
        ],
        "minOccurs": 1,
        "maxOccurs": 1
      }
    }
  ],
  "attributeGroups": []
}

export default dmlWordprocessingDrawingSchema