/**
 * Auto-generated from shared-bibliography.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedBibliographySchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/bibliography",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/sharedTypes",
      "schemaLocation": "shared-commonSimpleTypes.xsd"
    }
  ],
  "simpleTypes": [
    {
      "name": "ST_SourceType",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "external",
          "prefix": "s",
          "name": "ST_String"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "ArticleInAPeriodical",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Book",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "BookSection",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "JournalArticle",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ConferenceProceedings",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Report",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "SoundRecording",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Performance",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Art",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "DocumentFromInternetSite",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "InternetSite",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Film",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Interview",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Patent",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ElectronicSource",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Case",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "Misc",
            "fixed": false
          }
        ]
      }
    }
  ],
  "complexTypes": [
    {
      "name": "CT_NameListType",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_PersonType",
              "name": "Person",
              "minOccurs": 1,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_PersonType",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "s:ST_String",
              "name": "Last",
              "minOccurs": 0,
              "maxOccurs": -1,
              "nillable": false
            },
            {
              "type": "s:ST_String",
              "name": "First",
              "minOccurs": 0,
              "maxOccurs": -1,
              "nillable": false
            },
            {
              "type": "s:ST_String",
              "name": "Middle",
              "minOccurs": 0,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_NameType",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_NameListType",
              "name": "NameList",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_NameOrCorporateType",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "CT_NameListType",
                  "name": "NameList",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Corporate",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_AuthorType",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "CT_NameType",
                  "name": "Artist",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameOrCorporateType",
                  "name": "Author",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "BookAuthor",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Compiler",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Composer",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Conductor",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Counsel",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Director",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Editor",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Interviewee",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Interviewer",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Inventor",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameOrCorporateType",
                  "name": "Performer",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "ProducerName",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Translator",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_NameType",
                  "name": "Writer",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SourceType",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "s:ST_String",
                  "name": "AbbreviatedCaseNumber",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "AlbumTitle",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_AuthorType",
                  "name": "Author",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "BookTitle",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Broadcaster",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "BroadcastTitle",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "CaseNumber",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "ChapterNumber",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "City",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Comments",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "ConferenceName",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "CountryRegion",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Court",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Day",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "DayAccessed",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Department",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Distributor",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Edition",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Guid",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Institution",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "InternetSiteTitle",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Issue",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "JournalName",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_Lang",
                  "name": "LCID",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Medium",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Month",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "MonthAccessed",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "NumberVolumes",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Pages",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "PatentNumber",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "PeriodicalTitle",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "ProductionCompany",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "PublicationTitle",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Publisher",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "RecordingNumber",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "RefOrder",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Reporter",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "ST_SourceType",
                  "name": "SourceType",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "ShortTitle",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "StandardNumber",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "StateProvince",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Station",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Tag",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Theater",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "ThesisType",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Title",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Type",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "URL",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Version",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Volume",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "Year",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "s:ST_String",
                  "name": "YearAccessed",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Sources",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "SelectedStyle",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_String"
          },
          "use": "optional"
        },
        {
          "name": "StyleName",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_String"
          },
          "use": "optional"
        },
        {
          "name": "URI",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_String"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_SourceType",
              "name": "Source",
              "minOccurs": 0,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [
    {
      "name": "Sources",
      "type": {
        "kind": "local",
        "name": "CT_Sources"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [],
  "attributeGroups": []
}

export default sharedBibliographySchema