/**
 * Auto-generated from shared-documentPropertiesCustom.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedDocumentPropertiesCustomSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/customProperties",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/docPropsVTypes",
      "schemaLocation": "shared-documentPropertiesVariantTypes.xsd"
    },
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/sharedTypes",
      "schemaLocation": "shared-commonSimpleTypes.xsd"
    }
  ],
  "simpleTypes": [],
  "complexTypes": [
    {
      "name": "CT_Properties",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Property",
              "name": "property",
              "minOccurs": 0,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Property",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "fmtid",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_Guid"
          },
          "use": "required"
        },
        {
          "name": "pid",
          "type": {
            "kind": "builtin",
            "name": "int"
          },
          "use": "required"
        },
        {
          "name": "name",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "linkTarget",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "choice",
          "particles": [
            {
              "name": "",
              "ref": "vt:vector",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:array",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:blob",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:oblob",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:empty",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:null",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:i1",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:i2",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:i4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:i8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:int",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:ui1",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:ui2",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:ui4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:ui8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:uint",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:r4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:r8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:decimal",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:lpstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:lpwstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:bstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:date",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:filetime",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:bool",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:cy",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:error",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:stream",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:ostream",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:storage",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:ostorage",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:vstream",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vt:clsid",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [
    {
      "name": "Properties",
      "type": {
        "kind": "local",
        "name": "CT_Properties"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [],
  "attributeGroups": []
}

export default sharedDocumentPropertiesCustomSchema