/**
 * Auto-generated from shared-customXmlDataProperties.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedCustomXmlDataPropertiesSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/customXml",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/sharedTypes",
      "schemaLocation": "shared-commonSimpleTypes.xsd"
    }
  ],
  "simpleTypes": [],
  "complexTypes": [
    {
      "name": "CT_DatastoreSchemaRef",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "uri",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_DatastoreSchemaRefs",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_DatastoreSchemaRef",
              "name": "schemaRef",
              "minOccurs": 0,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_DatastoreItem",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "itemID",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_Guid"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_DatastoreSchemaRefs",
              "name": "schemaRefs",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [
    {
      "name": "datastoreItem",
      "type": {
        "kind": "local",
        "name": "CT_DatastoreItem"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [],
  "attributeGroups": []
}

export default sharedCustomXmlDataPropertiesSchema