/**
 * Auto-generated from shared-documentPropertiesVariantTypes.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedDocumentPropertiesVariantTypesSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/docPropsVTypes",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/sharedTypes",
      "schemaLocation": "shared-commonSimpleTypes.xsd"
    }
  ],
  "simpleTypes": [
    {
      "name": "ST_VectorBaseType",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "variant",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "i1",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "i2",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "i4",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "i8",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ui1",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ui2",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ui4",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ui8",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "r4",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "r8",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "lpstr",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "lpwstr",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bstr",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "date",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "filetime",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bool",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "cy",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "error",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "clsid",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_ArrayBaseType",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "variant",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "i1",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "i2",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "i4",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "int",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ui1",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ui2",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "ui4",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "uint",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "r4",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "r8",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "decimal",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bstr",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "date",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bool",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "cy",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "error",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Cy",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "\\s*[0-9]*\\.[0-9]{4}\\s*",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Error",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "\\s*0x[0-9A-Za-z]{8}\\s*",
            "fixed": false
          }
        ]
      }
    }
  ],
  "complexTypes": [
    {
      "name": "CT_Empty",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Null",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Vector",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "baseType",
          "type": {
            "kind": "local",
            "name": "ST_VectorBaseType"
          },
          "use": "required"
        },
        {
          "name": "size",
          "type": {
            "kind": "builtin",
            "name": "unsignedInt"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "choice",
          "particles": [
            {
              "name": "",
              "ref": "variant",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i1",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i2",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui1",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui2",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "r4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "r8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "lpstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "lpwstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "bstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "date",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "filetime",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "bool",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "cy",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "error",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "clsid",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Array",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "lBounds",
          "type": {
            "kind": "builtin",
            "name": "int"
          },
          "use": "required"
        },
        {
          "name": "uBounds",
          "type": {
            "kind": "builtin",
            "name": "int"
          },
          "use": "required"
        },
        {
          "name": "baseType",
          "type": {
            "kind": "local",
            "name": "ST_ArrayBaseType"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "choice",
          "particles": [
            {
              "name": "",
              "ref": "variant",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i1",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i2",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "int",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui1",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui2",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "uint",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "r4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "r8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "decimal",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "bstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "date",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "bool",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "error",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "cy",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Variant",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "choice",
          "particles": [
            {
              "name": "",
              "ref": "variant",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vector",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "array",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "blob",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "oblob",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "empty",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "null",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i1",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i2",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "i8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "int",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui1",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui2",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ui8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "uint",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "r4",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "r8",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "decimal",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "lpstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "lpwstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "bstr",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "date",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "filetime",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "bool",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "cy",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "error",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "stream",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ostream",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "storage",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "ostorage",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "vstream",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "name": "",
              "ref": "clsid",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Vstream",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "simpleContent",
        "derivation": "extension",
        "base": {
          "kind": "builtin",
          "name": "base64Binary"
        },
        "attributes": [
          {
            "name": "version",
            "type": {
              "kind": "external",
              "prefix": "s",
              "name": "ST_Guid"
            },
            "use": "optional"
          }
        ]
      }
    }
  ],
  "elements": [
    {
      "name": "variant",
      "type": {
        "kind": "local",
        "name": "CT_Variant"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "vector",
      "type": {
        "kind": "local",
        "name": "CT_Vector"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "array",
      "type": {
        "kind": "local",
        "name": "CT_Array"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "blob",
      "type": {
        "kind": "builtin",
        "name": "base64Binary"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "oblob",
      "type": {
        "kind": "builtin",
        "name": "base64Binary"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "empty",
      "type": {
        "kind": "local",
        "name": "CT_Empty"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "null",
      "type": {
        "kind": "local",
        "name": "CT_Null"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "i1",
      "type": {
        "kind": "builtin",
        "name": "byte"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "i2",
      "type": {
        "kind": "builtin",
        "name": "short"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "i4",
      "type": {
        "kind": "builtin",
        "name": "int"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "i8",
      "type": {
        "kind": "builtin",
        "name": "long"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "int",
      "type": {
        "kind": "builtin",
        "name": "int"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "ui1",
      "type": {
        "kind": "builtin",
        "name": "unsignedByte"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "ui2",
      "type": {
        "kind": "builtin",
        "name": "unsignedShort"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "ui4",
      "type": {
        "kind": "builtin",
        "name": "unsignedInt"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "ui8",
      "type": {
        "kind": "builtin",
        "name": "unsignedLong"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "uint",
      "type": {
        "kind": "builtin",
        "name": "unsignedInt"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "r4",
      "type": {
        "kind": "builtin",
        "name": "float"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "r8",
      "type": {
        "kind": "builtin",
        "name": "double"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "decimal",
      "type": {
        "kind": "builtin",
        "name": "decimal"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "lpstr",
      "type": {
        "kind": "builtin",
        "name": "string"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "lpwstr",
      "type": {
        "kind": "builtin",
        "name": "string"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "bstr",
      "type": {
        "kind": "builtin",
        "name": "string"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "date",
      "type": {
        "kind": "builtin",
        "name": "dateTime"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "filetime",
      "type": {
        "kind": "builtin",
        "name": "dateTime"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "bool",
      "type": {
        "kind": "builtin",
        "name": "boolean"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "cy",
      "type": {
        "kind": "local",
        "name": "ST_Cy"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "error",
      "type": {
        "kind": "local",
        "name": "ST_Error"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "stream",
      "type": {
        "kind": "builtin",
        "name": "base64Binary"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "ostream",
      "type": {
        "kind": "builtin",
        "name": "base64Binary"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "storage",
      "type": {
        "kind": "builtin",
        "name": "base64Binary"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "ostorage",
      "type": {
        "kind": "builtin",
        "name": "base64Binary"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "vstream",
      "type": {
        "kind": "local",
        "name": "CT_Vstream"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "clsid",
      "type": {
        "kind": "external",
        "prefix": "s",
        "name": "ST_Guid"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [],
  "attributeGroups": []
}

export default sharedDocumentPropertiesVariantTypesSchema