/**
 * Auto-generated from shared-customXmlSchemaProperties.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedCustomXmlSchemaPropertiesSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/schemaLibrary/main",
  "imports": [],
  "simpleTypes": [],
  "complexTypes": [
    {
      "name": "CT_Schema",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "uri",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional",
          "default": ""
        },
        {
          "name": "manifestLocation",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "schemaLocation",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "optional"
        },
        {
          "name": "schemaLanguage",
          "type": {
            "kind": "builtin",
            "name": "token"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_SchemaLibrary",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Schema",
              "name": "schema",
              "minOccurs": 0,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [
    {
      "name": "schemaLibrary",
      "type": {
        "kind": "local",
        "name": "CT_SchemaLibrary"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [],
  "attributeGroups": []
}

export default sharedCustomXmlSchemaPropertiesSchema