/**
 * Auto-generated from shared-documentPropertiesExtended.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedDocumentPropertiesExtendedSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/extendedProperties",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/docPropsVTypes",
      "schemaLocation": "shared-documentPropertiesVariantTypes.xsd"
    }
  ],
  "simpleTypes": [],
  "complexTypes": [
    {
      "name": "CT_Properties",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "all",
          "particles": [
            {
              "type": "xsd:string",
              "name": "Template",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:string",
              "name": "Manager",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:string",
              "name": "Company",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "Pages",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "Words",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "Characters",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:string",
              "name": "PresentationFormat",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "Lines",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "Paragraphs",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "Slides",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "Notes",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "TotalTime",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "HiddenSlides",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "MMClips",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:boolean",
              "name": "ScaleCrop",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_VectorVariant",
              "name": "HeadingPairs",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_VectorLpstr",
              "name": "TitlesOfParts",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:boolean",
              "name": "LinksUpToDate",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "CharactersWithSpaces",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:boolean",
              "name": "SharedDoc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:string",
              "name": "HyperlinkBase",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_VectorVariant",
              "name": "HLinks",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:boolean",
              "name": "HyperlinksChanged",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_DigSigBlob",
              "name": "DigSig",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:string",
              "name": "Application",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:string",
              "name": "AppVersion",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "xsd:int",
              "name": "DocSecurity",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_VectorVariant",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "name": "",
              "ref": "vt:vector",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_VectorLpstr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "name": "",
              "ref": "vt:vector",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_DigSigBlob",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "name": "",
              "ref": "vt:blob",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [
    {
      "name": "Properties",
      "type": {
        "kind": "local",
        "name": "CT_Properties"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [],
  "attributeGroups": []
}

export default sharedDocumentPropertiesExtendedSchema