/**
 * Auto-generated from shared-relationshipReference.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedRelationshipReferenceSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/relationships",
  "imports": [],
  "simpleTypes": [
    {
      "name": "ST_RelationshipId",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": []
      }
    }
  ],
  "complexTypes": [],
  "elements": [],
  "groups": [],
  "attributeGroups": []
}

export default sharedRelationshipReferenceSchema