/**
 * Auto-generated from shared-additionalCharacteristics.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedAdditionalCharacteristicsSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/characteristics",
  "imports": [],
  "simpleTypes": [
    {
      "name": "ST_Relation",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "ge",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "le",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "gt",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "lt",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "eq",
            "fixed": false
          }
        ]
      }
    }
  ],
  "complexTypes": [
    {
      "name": "CT_AdditionalCharacteristics",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Characteristic",
              "name": "characteristic",
              "minOccurs": 0,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Characteristic",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "name",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "required"
        },
        {
          "name": "relation",
          "type": {
            "kind": "local",
            "name": "ST_Relation"
          },
          "use": "required"
        },
        {
          "name": "val",
          "type": {
            "kind": "builtin",
            "name": "string"
          },
          "use": "required"
        },
        {
          "name": "vocabulary",
          "type": {
            "kind": "builtin",
            "name": "anyURI"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    }
  ],
  "elements": [
    {
      "name": "additionalCharacteristics",
      "type": {
        "kind": "local",
        "name": "CT_AdditionalCharacteristics"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [],
  "attributeGroups": []
}

export default sharedAdditionalCharacteristicsSchema