/**
 * Auto-generated from shared-commonSimpleTypes.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedCommonSimpleTypesSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/sharedTypes",
  "imports": [],
  "simpleTypes": [
    {
      "name": "ST_Lang",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": []
      }
    },
    {
      "name": "ST_HexColorRGB",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "hexBinary"
        },
        "facets": [
          {
            "kind": "length",
            "value": "3",
            "fixed": true
          }
        ]
      }
    },
    {
      "name": "ST_Panose",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "hexBinary"
        },
        "facets": [
          {
            "kind": "length",
            "value": "10",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_CalendarType",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "gregorian",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "gregorianUs",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "gregorianMeFrench",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "gregorianArabic",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "hijri",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "hebrew",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "taiwan",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "japan",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "thai",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "korea",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "saka",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "gregorianXlitEnglish",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "gregorianXlitFrench",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "none",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Guid",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "token"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_OnOff",
      "content": {
        "kind": "union",
        "memberTypes": [
          {
            "kind": "builtin",
            "name": "boolean"
          }
        ]
      }
    },
    {
      "name": "ST_String",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": []
      }
    },
    {
      "name": "ST_XmlName",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "NCName"
        },
        "facets": [
          {
            "kind": "minLength",
            "value": "1",
            "fixed": false
          },
          {
            "kind": "maxLength",
            "value": "255",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_UnsignedDecimalNumber",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "unsignedLong"
        },
        "facets": []
      }
    },
    {
      "name": "ST_TwipsMeasure",
      "content": {
        "kind": "union",
        "memberTypes": [
          {
            "kind": "local",
            "name": "ST_UnsignedDecimalNumber"
          },
          {
            "kind": "local",
            "name": "ST_PositiveUniversalMeasure"
          }
        ]
      }
    },
    {
      "name": "ST_VerticalAlignRun",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "baseline",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "superscript",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "subscript",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Xstring",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": []
      }
    },
    {
      "name": "ST_XAlign",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "left",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "center",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "right",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "inside",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "outside",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_YAlign",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "inline",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "top",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "center",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bottom",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "inside",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "outside",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_ConformanceClass",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "strict",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "transitional",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_UniversalMeasure",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "-?[0-9]+(\\.[0-9]+)?(mm|cm|in|pt|pc|pi)",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_PositiveUniversalMeasure",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "local",
          "name": "ST_UniversalMeasure"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "[0-9]+(\\.[0-9]+)?(mm|cm|in|pt|pc|pi)",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Percentage",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "-?[0-9]+(\\.[0-9]+)?%",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_FixedPercentage",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "local",
          "name": "ST_Percentage"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "-?((100)|([0-9][0-9]?))(\\.[0-9][0-9]?)?%",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_PositivePercentage",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "local",
          "name": "ST_Percentage"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "[0-9]+(\\.[0-9]+)?%",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_PositiveFixedPercentage",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "local",
          "name": "ST_Percentage"
        },
        "facets": [
          {
            "kind": "pattern",
            "value": "((100)|([0-9][0-9]?))(\\.[0-9][0-9]?)?%",
            "fixed": false
          }
        ]
      }
    }
  ],
  "complexTypes": [],
  "elements": [],
  "groups": [],
  "attributeGroups": []
}

export default sharedCommonSimpleTypesSchema