/**
 * Auto-generated from shared-math.xsd
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema, XsdSimpleType, XsdComplexType, XsdElement, XsdGroup, XsdAttributeGroup } from '../types'

export const sharedMathSchema: XsdSchema = {
  "targetNamespace": "http://purl.oclc.org/ooxml/officeDocument/math",
  "imports": [
    {
      "namespace": "http://purl.oclc.org/ooxml/wordprocessingml/main",
      "schemaLocation": "wml.xsd"
    },
    {
      "namespace": "http://purl.oclc.org/ooxml/officeDocument/sharedTypes",
      "schemaLocation": "shared-commonSimpleTypes.xsd"
    },
    {
      "namespace": "http://www.w3.org/XML/1998/namespace",
      "schemaLocation": ""
    }
  ],
  "simpleTypes": [
    {
      "name": "ST_Integer255",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "integer"
        },
        "facets": [
          {
            "kind": "minInclusive",
            "value": "1",
            "fixed": false
          },
          {
            "kind": "maxInclusive",
            "value": "255",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Integer2",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "integer"
        },
        "facets": [
          {
            "kind": "minInclusive",
            "value": "-2",
            "fixed": false
          },
          {
            "kind": "maxInclusive",
            "value": "2",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_SpacingRule",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "integer"
        },
        "facets": [
          {
            "kind": "minInclusive",
            "value": "0",
            "fixed": false
          },
          {
            "kind": "maxInclusive",
            "value": "4",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_UnSignedInteger",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "unsignedInt"
        },
        "facets": []
      }
    },
    {
      "name": "ST_Char",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "maxLength",
            "value": "1",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Shp",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "centered",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "match",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_FType",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "bar",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "skw",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "lin",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "noBar",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_LimLoc",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "undOvr",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "subSup",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_TopBot",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "top",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bot",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Script",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "roman",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "script",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "fraktur",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "double-struck",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "sans-serif",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "monospace",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Style",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "p",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "b",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "i",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "bi",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_Jc",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "left",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "right",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "center",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "centerGroup",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_BreakBin",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "before",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "after",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "repeat",
            "fixed": false
          }
        ]
      }
    },
    {
      "name": "ST_BreakBinSub",
      "content": {
        "kind": "restriction",
        "base": {
          "kind": "builtin",
          "name": "string"
        },
        "facets": [
          {
            "kind": "enumeration",
            "value": "--",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "-+",
            "fixed": false
          },
          {
            "kind": "enumeration",
            "value": "+-",
            "fixed": false
          }
        ]
      }
    }
  ],
  "complexTypes": [
    {
      "name": "CT_Integer255",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_Integer255"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Integer2",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_Integer2"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_SpacingRule",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_SpacingRule"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_UnSignedInteger",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_UnSignedInteger"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Char",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_Char"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_OnOff",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_OnOff"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_String",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_String"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_XAlign",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_XAlign"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_YAlign",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_YAlign"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Shp",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_Shp"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_FType",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_FType"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_LimLoc",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_LimLoc"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_TopBot",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_TopBot"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Script",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_Script"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_Style",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_Style"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_ManualBreak",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "alnAt",
          "type": {
            "kind": "local",
            "name": "ST_Integer255"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_RPR",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OnOff",
              "name": "lit",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_ManualBreak",
              "name": "brk",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "aln",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "CT_OnOff",
                  "name": "nor",
                  "minOccurs": 0,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "kind": "sequence",
                  "particles": [
                    {
                      "kind": "group",
                      "ref": {
                        "kind": "local",
                        "name": "EG_ScriptStyle"
                      },
                      "minOccurs": 1,
                      "maxOccurs": 1
                    }
                  ],
                  "minOccurs": 1,
                  "maxOccurs": 1
                }
              ],
              "minOccurs": 1,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Text",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "simpleContent",
        "derivation": "extension",
        "base": {
          "kind": "external",
          "prefix": "s",
          "name": "ST_String"
        },
        "attributes": [
          {
            "name": "",
            "ref": {
              "kind": "external",
              "prefix": "xml",
              "name": "space"
            },
            "type": {
              "kind": "builtin",
              "name": "string"
            },
            "use": "optional"
          }
        ]
      }
    },
    {
      "name": "CT_R",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_RPR",
              "name": "rPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "CT_Text",
                  "name": "t",
                  "minOccurs": 0,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "kind": "group",
                  "ref": {
                    "kind": "external",
                    "prefix": "w",
                    "name": "EG_RunInnerContent"
                  },
                  "minOccurs": 1,
                  "maxOccurs": 1
                }
              ],
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            },
            {
              "kind": "group",
              "ref": {
                "kind": "external",
                "prefix": "w",
                "name": "EG_RPr"
              },
              "minOccurs": 0,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_CtrlPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "group",
              "ref": {
                "kind": "external",
                "prefix": "w",
                "name": "EG_RPrMath"
              },
              "minOccurs": 0,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_AccPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Char",
              "name": "chr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Acc",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_AccPr",
              "name": "accPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_BarPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_TopBot",
              "name": "pos",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Bar",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_BarPr",
              "name": "barPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_BoxPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OnOff",
              "name": "opEmu",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "noBreak",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "diff",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_ManualBreak",
              "name": "brk",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "aln",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Box",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_BoxPr",
              "name": "boxPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_BorderBoxPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OnOff",
              "name": "hideTop",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "hideBot",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "hideLeft",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "hideRight",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "strikeH",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "strikeV",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "strikeBLTR",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "strikeTLBR",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_BorderBox",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_BorderBoxPr",
              "name": "borderBoxPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_DPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Char",
              "name": "begChr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_Char",
              "name": "sepChr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_Char",
              "name": "endChr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "grow",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_Shp",
              "name": "shp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_D",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_DPr",
              "name": "dPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_EqArrPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_YAlign",
              "name": "baseJc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "maxDist",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "objDist",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_SpacingRule",
              "name": "rSpRule",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_UnSignedInteger",
              "name": "rSp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_EqArr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_EqArrPr",
              "name": "eqArrPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_FPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_FType",
              "name": "type",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_F",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_FPr",
              "name": "fPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "num",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "den",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_FuncPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Func",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_FuncPr",
              "name": "funcPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "fName",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GroupChrPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Char",
              "name": "chr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_TopBot",
              "name": "pos",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_TopBot",
              "name": "vertJc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_GroupChr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_GroupChrPr",
              "name": "groupChrPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_LimLowPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_LimLow",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_LimLowPr",
              "name": "limLowPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "lim",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_LimUppPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_LimUpp",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_LimUppPr",
              "name": "limUppPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "lim",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_MCPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Integer255",
              "name": "count",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_XAlign",
              "name": "mcJc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_MC",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_MCPr",
              "name": "mcPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_MCS",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_MC",
              "name": "mc",
              "minOccurs": 1,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_MPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_YAlign",
              "name": "baseJc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "plcHide",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_SpacingRule",
              "name": "rSpRule",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_SpacingRule",
              "name": "cGpRule",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_UnSignedInteger",
              "name": "rSp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_UnSignedInteger",
              "name": "cSp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_UnSignedInteger",
              "name": "cGp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_MCS",
              "name": "mcs",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_MR",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_M",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_MPr",
              "name": "mPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_MR",
              "name": "mr",
              "minOccurs": 1,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_NaryPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Char",
              "name": "chr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_LimLoc",
              "name": "limLoc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "grow",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "subHide",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "supHide",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Nary",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_NaryPr",
              "name": "naryPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "sub",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "sup",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_PhantPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OnOff",
              "name": "show",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "zeroWid",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "zeroAsc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "zeroDesc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "transp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Phant",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_PhantPr",
              "name": "phantPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_RadPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OnOff",
              "name": "degHide",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_Rad",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_RadPr",
              "name": "radPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "deg",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SPrePr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SPre",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_SPrePr",
              "name": "sPrePr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "sub",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "sup",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SSubPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SSub",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_SSubPr",
              "name": "sSubPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "sub",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SSubSupPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OnOff",
              "name": "alnScr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SSubSup",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_SSubSupPr",
              "name": "sSubSupPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "sub",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "sup",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SSupPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_SSup",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_SSupPr",
              "name": "sSupPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "e",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathArg",
              "name": "sup",
              "minOccurs": 1,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_OMathArgPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_Integer2",
              "name": "argSz",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_OMathArg",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OMathArgPr",
              "name": "argPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_CtrlPr",
              "name": "ctrlPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_OMathElements"
              },
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_OMathJc",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_Jc"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_OMathParaPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OMathJc",
              "name": "jc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_TwipsMeasure",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "external",
            "prefix": "s",
            "name": "ST_TwipsMeasure"
          },
          "use": "required"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_BreakBin",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_BreakBin"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_BreakBinSub",
      "mixed": false,
      "abstract": false,
      "attributes": [
        {
          "name": "val",
          "type": {
            "kind": "local",
            "name": "ST_BreakBinSub"
          },
          "use": "optional"
        }
      ],
      "attributeGroupRefs": [],
      "content": {
        "kind": "empty"
      }
    },
    {
      "name": "CT_MathPr",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_String",
              "name": "mathFont",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_BreakBin",
              "name": "brkBin",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_BreakBinSub",
              "name": "brkBinSub",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "smallFrac",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OnOff",
              "name": "dispDef",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_TwipsMeasure",
              "name": "lMargin",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_TwipsMeasure",
              "name": "rMargin",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMathJc",
              "name": "defJc",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_TwipsMeasure",
              "name": "preSp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_TwipsMeasure",
              "name": "postSp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_TwipsMeasure",
              "name": "interSp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_TwipsMeasure",
              "name": "intraSp",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_LimLoc",
              "name": "intLim",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_LimLoc",
              "name": "naryLim",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "kind": "choice",
              "particles": [
                {
                  "type": "CT_TwipsMeasure",
                  "name": "wrapIndent",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                },
                {
                  "type": "CT_OnOff",
                  "name": "wrapRight",
                  "minOccurs": 1,
                  "maxOccurs": 1,
                  "nillable": false
                }
              ],
              "minOccurs": 0,
              "maxOccurs": 1
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_OMathPara",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "type": "CT_OMathParaPr",
              "name": "oMathParaPr",
              "minOccurs": 0,
              "maxOccurs": 1,
              "nillable": false
            },
            {
              "type": "CT_OMath",
              "name": "oMath",
              "minOccurs": 1,
              "maxOccurs": -1,
              "nillable": false
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    },
    {
      "name": "CT_OMath",
      "mixed": false,
      "abstract": false,
      "attributes": [],
      "attributeGroupRefs": [],
      "content": {
        "kind": "elementOnly",
        "compositor": {
          "kind": "sequence",
          "particles": [
            {
              "kind": "group",
              "ref": {
                "kind": "local",
                "name": "EG_OMathElements"
              },
              "minOccurs": 0,
              "maxOccurs": "unbounded"
            }
          ],
          "minOccurs": 1,
          "maxOccurs": 1
        }
      }
    }
  ],
  "elements": [
    {
      "name": "mathPr",
      "type": {
        "kind": "local",
        "name": "CT_MathPr"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "oMathPara",
      "type": {
        "kind": "local",
        "name": "CT_OMathPara"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    },
    {
      "name": "oMath",
      "type": {
        "kind": "local",
        "name": "CT_OMath"
      },
      "minOccurs": 1,
      "maxOccurs": 1,
      "nillable": false
    }
  ],
  "groups": [
    {
      "name": "EG_ScriptStyle",
      "compositor": {
        "kind": "sequence",
        "particles": [
          {
            "type": "CT_Script",
            "name": "scr",
            "minOccurs": 0,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_Style",
            "name": "sty",
            "minOccurs": 0,
            "maxOccurs": 1,
            "nillable": false
          }
        ],
        "minOccurs": 1,
        "maxOccurs": 1
      }
    },
    {
      "name": "EG_OMathMathElements",
      "compositor": {
        "kind": "choice",
        "particles": [
          {
            "type": "CT_Acc",
            "name": "acc",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_Bar",
            "name": "bar",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_Box",
            "name": "box",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_BorderBox",
            "name": "borderBox",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_D",
            "name": "d",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_EqArr",
            "name": "eqArr",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_F",
            "name": "f",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_Func",
            "name": "func",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_GroupChr",
            "name": "groupChr",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_LimLow",
            "name": "limLow",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_LimUpp",
            "name": "limUpp",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_M",
            "name": "m",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_Nary",
            "name": "nary",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_Phant",
            "name": "phant",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_Rad",
            "name": "rad",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_SPre",
            "name": "sPre",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_SSub",
            "name": "sSub",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_SSubSup",
            "name": "sSubSup",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_SSup",
            "name": "sSup",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          },
          {
            "type": "CT_R",
            "name": "r",
            "minOccurs": 1,
            "maxOccurs": 1,
            "nillable": false
          }
        ],
        "minOccurs": 1,
        "maxOccurs": 1
      }
    },
    {
      "name": "EG_OMathElements",
      "compositor": {
        "kind": "choice",
        "particles": [
          {
            "kind": "group",
            "ref": {
              "kind": "local",
              "name": "EG_OMathMathElements"
            },
            "minOccurs": 1,
            "maxOccurs": 1
          },
          {
            "kind": "group",
            "ref": {
              "kind": "external",
              "prefix": "w",
              "name": "EG_PContentMath"
            },
            "minOccurs": 1,
            "maxOccurs": 1
          }
        ],
        "minOccurs": 1,
        "maxOccurs": 1
      }
    }
  ],
  "attributeGroups": []
}

export default sharedMathSchema