/**
 * XSD to JSON Schema Converter
 *
 * Converts OOXML XSD schema files to JSON runtime type definitions
 * for use with @ooxml/core validation engine.
 *
 * Usage:
 *   pnpm --filter xsd-converter convert
 *
 * This will:
 * 1. Read all XSD files from ../../schemas/
 * 2. Parse and convert to JSON schema format
 * 3. Output TypeScript files to ../../packages/core/src/schemas/
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SCHEMAS_DIR = join(__dirname, '../../../schemas')
const OUTPUT_DIR = join(__dirname, '../../../packages/core/src/schemas')

interface ConversionResult {
  filename: string
  success: boolean
  error?: string
  elementCount?: number
  typeCount?: number
}

async function main(): Promise<void> {
  console.log('XSD to JSON Schema Converter')
  console.log('============================')
  console.log(`Input: ${SCHEMAS_DIR}`)
  console.log(`Output: ${OUTPUT_DIR}`)
  console.log('')

  // Ensure output directory exists
  mkdirSync(OUTPUT_DIR, { recursive: true })

  // Find all XSD files
  const xsdFiles = readdirSync(SCHEMAS_DIR).filter((f) => f.endsWith('.xsd'))
  console.log(`Found ${xsdFiles.length} XSD files`)
  console.log('')

  const results: ConversionResult[] = []

  for (const xsdFile of xsdFiles) {
    console.log(`Processing: ${xsdFile}`)

    try {
      const xsdPath = join(SCHEMAS_DIR, xsdFile)
      const xsdContent = readFileSync(xsdPath, 'utf-8')

      // TODO: Implement actual XSD parsing and conversion
      // For now, create a placeholder
      const result = await convertXsdToJson(xsdFile, xsdContent)

      results.push({
        filename: xsdFile,
        success: true,
        elementCount: result.elementCount,
        typeCount: result.typeCount,
      })

      console.log(`  ✓ Converted: ${result.elementCount} elements, ${result.typeCount} types`)
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error)
      results.push({
        filename: xsdFile,
        success: false,
        error: errorMessage,
      })
      console.log(`  ✗ Error: ${errorMessage}`)
    }
  }

  // Summary
  console.log('')
  console.log('Summary')
  console.log('-------')
  const successCount = results.filter((r) => r.success).length
  console.log(`Success: ${successCount}/${results.length}`)

  if (successCount < results.length) {
    console.log('Failed files:')
    results
      .filter((r) => !r.success)
      .forEach((r) => {
        console.log(`  - ${r.filename}: ${r.error}`)
      })
  }

  // Generate index file
  generateIndexFile(results.filter((r) => r.success))
}

interface ConversionOutput {
  elementCount: number
  typeCount: number
}

async function convertXsdToJson(filename: string, _content: string): Promise<ConversionOutput> {
  // TODO: Implement XSD parsing
  // This is a placeholder that creates empty schema files

  const baseName = filename.replace('.xsd', '')
  const outputPath = join(OUTPUT_DIR, `${baseName}.ts`)

  const placeholderContent = `/**
 * Auto-generated from ${filename}
 * DO NOT EDIT - Generated by xsd-converter
 */

import type { XsdSchema } from '../types'

export const ${camelCase(baseName)}Schema: XsdSchema = {
  targetNamespace: '',
  elements: [],
  complexTypes: [],
  simpleTypes: [],
  groups: [],
  attributeGroups: [],
}

export default ${camelCase(baseName)}Schema
`

  writeFileSync(outputPath, placeholderContent)

  return {
    elementCount: 0,
    typeCount: 0,
  }
}

function generateIndexFile(results: ConversionResult[]): void {
  const imports = results
    .map((r) => {
      const baseName = r.filename.replace('.xsd', '')
      const varName = camelCase(baseName)
      return `export { ${varName}Schema } from './${baseName}'`
    })
    .join('\n')

  const indexContent = `/**
 * Auto-generated schema index
 * DO NOT EDIT - Generated by xsd-converter
 */

${imports}
`

  writeFileSync(join(OUTPUT_DIR, 'index.ts'), indexContent)
  console.log(`Generated: ${OUTPUT_DIR}/index.ts`)
}

function camelCase(str: string): string {
  return str
    .split('-')
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('')
}

main().catch(console.error)
